Repository spring-projects-experimental/spring-native, pull requests merged in 2021-07, with the labels that each got.

#883 Fix typo
  spring-native-docs/src/main/asciidoc/executable-jar-to-native.adoc
Labels: status: waiting-for-triage

#876 #868 - Aspect on Repository not called
  spring-native-configuration/src/main/java/org/springframework/boot/autoconfigure/aop/AopHints.java
Labels: status: waiting-for-triage

#866 #861 - Proxies for @Validated components not prepared
  samples/validator/src/main/java/com/example/validator/hierarchy/ComponentWithValidatedInterface.java
  samples/validator/src/main/java/com/example/validator/hierarchy/ComponentWithValidatedInterfaceAndExtraInterface.java
  samples/validator/src/main/java/com/example/validator/hierarchy/ComponentWithValidatedInterfaceOverProxyClass.java
  samples/validator/src/main/java/com/example/validator/hierarchy/ComponentWithValidatedInterfaceOverProxyInterface.java
  samples/validator/src/main/java/com/example/validator/hierarchy/ComponentWithValidatedInterfaceWithDefault.java
  samples/validator/src/main/java/com/example/validator/hierarchy/ComponentWithValidatedInterfaceWithoutMethod.java
  samples/validator/src/main/java/com/example/validator/hierarchy/ProxyClass.java
  samples/validator/src/main/java/com/example/validator/hierarchy/ProxyInterface.java
  samples/validator/src/main/java/com/example/validator/hierarchy/ValidatedComponent.java
  samples/validator/src/main/java/com/example/validator/hierarchy/ValidatedInterface.java
  samples/validator/src/main/java/com/example/validator/hierarchy/ValidatedInterfaceWithDefault.java
  samples/validator/src/main/java/com/example/validator/hierarchy/ValidatedInterfaceWithoutMethod.java
  samples/validator/src/main/java/com/example/validator/hierarchy/VoidInterface.java
  spring-aot/src/main/java/org/springframework/nativex/type/Type.java
  spring-native-configuration/src/main/java/org/springframework/ValidatedComponentProcessor.java
  spring-native-configuration/src/main/resources/META-INF/services/org.springframework.nativex.type.ComponentProcessor
  spring-native-configuration/src/test/java/org/springframework/nativex/util/NativeTestContext.java
  spring-native-configuration/src/test/java/org/springframework/validated/ValidatedComponentProcessorTest.java
  spring-native-configuration/src/test/java/org/springframework/validated/components/ComponentWithValidatedInterface.java
  spring-native-configuration/src/test/java/org/springframework/validated/components/ComponentWithValidatedInterfaceAndExtraInterface.java
  spring-native-configuration/src/test/java/org/springframework/validated/components/ComponentWithValidatedInterfaceOverProxyClass.java
  spring-native-configuration/src/test/java/org/springframework/validated/components/ComponentWithValidatedInterfaceOverProxyInterface.java
  spring-native-configuration/src/test/java/org/springframework/validated/components/ComponentWithValidatedInterfaceWithDefault.java
  spring-native-configuration/src/test/java/org/springframework/validated/components/ComponentWithValidatedInterfaceWithoutMethod.java
  spring-native-configuration/src/test/java/org/springframework/validated/components/ProxyClass.java
  spring-native-configuration/src/test/java/org/springframework/validated/components/ProxyInterface.java
  spring-native-configuration/src/test/java/org/springframework/validated/components/ValidatedComponent.java
  spring-native-configuration/src/test/java/org/springframework/validated/components/ValidatedInterface.java
  spring-native-configuration/src/test/java/org/springframework/validated/components/ValidatedInterfaceWithDefault.java
  spring-native-configuration/src/test/java/org/springframework/validated/components/ValidatedInterfaceWithoutMethod.java
  spring-native-configuration/src/test/java/org/springframework/validated/components/VoidInterface.java
Labels: type: compatibility

#897 Enable exclusion of certain reflection entries during build
  spring-aot/src/main/java/org/springframework/nativex/support/ConfigurationCollector.java
Labels: type: enhancement

#899 Allow TypeSystem to scan dependencies.
  spring-aot/src/main/java/org/springframework/nativex/type/TypeSystem.java
Labels: type: enhancement

#932 Use target class version for proxy
  spring-native/src/main/java/org/springframework/aop/framework/ProxyGenerator.java
Labels: status: waiting-for-triage

#946 Fix Gradle task name in sample README
  samples/commandlinerunner-gradle/README.md
Labels: status: waiting-for-triage
