Repository spring-projects-experimental/spring-native, pull requests merged in 2021-09, with the labels that each got.

#1060 Slight update to Spring IntegrationHints & sample
  samples/integration/build.sh
  samples/integration/docker-compose.yml
  spring-native-configuration/src/main/java/org/springframework/integration/IntegrationHints.java
Labels: status: waiting-for-triage

#1064 Fix discovery-client sample config.
  samples/cloud-discovery/discoveryclient/pom.xml
  samples/cloud-discovery/discoveryclient/src/main/resources/application.properties
  samples/cloud-discovery/discoveryclient/src/main/resources/bootstrap.properties
Labels: status: waiting-for-triage

#1083 Removing hint that is unnecessary for 0.11.x
  spring-native-configuration/src/main/java/org/springframework/cloud/task/CloudTaskHints.java
Labels: status: waiting-for-triage

#1082 Remove configclient. Rename configclient-new to configclient.
  samples/cloud-config/configclient-new/README.md
  samples/cloud-config/configclient-new/build-without-server-build.sh
  samples/cloud-config/configclient-new/build.sh
  samples/cloud-config/configclient-new/pom.xml
  samples/cloud-config/configclient-new/src/main/java/com/example/configclient/ConfigclientApplication.java
  samples/cloud-config/configclient-new/src/main/resources/application.properties
  samples/cloud-config/configclient-new/src/test/java/com/example/configclient/ConfigclientApplicationTests.java
  samples/cloud-config/configclient-new/verify.sh
  samples/cloud-config/configclient/README.md
  samples/cloud-config/configclient/pom.xml
  samples/cloud-config/configclient/src/main/resources/application.properties
  samples/cloud-config/configclient/src/main/resources/bootstrap.properties
  samples/cloud-config/configclient/verify.sh
  spring-native-configuration/src/main/java/org/springframework/boot/SpringBootHints.java
Labels: type: task

#1081 Update Spring Cloud support docs.
  spring-native-docs/src/main/asciidoc/support.adoc
Labels: type: documentation, status: waiting-for-triage

#1077 Add missing --enable-http option.
  spring-native-configuration/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientHints.java
Labels: status: waiting-for-triage

#1085 Change the maven default remote debug port from 5005 to 8000
  spring-aot-maven-plugin/src/main/java/org/springframework/aot/maven/GenerateMojo.java
  spring-native-docs/src/main/asciidoc/spring-aot.adoc
Labels: type: task

#1086 Update reflection config for the data-rest sample.
  spring-native-configuration/src/main/java/org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaHints.java
Labels: type: compatibility

#1004 Fix to repeated interface error
  spring-aot/src/main/java/org/springframework/nativex/domain/proxies/AotProxyDescriptor.java
  spring-aot/src/main/java/org/springframework/nativex/domain/proxies/JdkProxyDescriptor.java
  spring-aot/src/main/java/org/springframework/nativex/domain/proxies/ProxiesDescriptor.java
  spring-aot/src/main/java/org/springframework/nativex/domain/proxies/ProxiesDescriptorJsonConverter.java
  spring-aot/src/main/java/org/springframework/nativex/domain/proxies/ProxiesDescriptorJsonMarshaller.java
  spring-aot/src/main/java/org/springframework/nativex/support/ConfigurationCollector.java
  spring-aot/src/main/java/org/springframework/nativex/support/DynamicProxiesHandler.java
  spring-aot/src/test/java/org/springframework/nativex/DescriptorTests.java
  spring-aot/src/test/java/org/springframework/nativex/HintTests.java
  spring-native-configuration/src/test/java/org/springframework/nativex/util/HintDeclarationAssert.java
  spring-native/src/main/java/org/springframework/aop/framework/BuildTimeProxyDescriptor.java
Labels: type: bug

#1100 Append context initializers in aot mode
  spring-native/src/main/java/org/springframework/boot/SpringApplication.java
  spring-native/src/main/java/org/springframework/boot/Target_SpringApplication.java
Labels: type: bug

#1104 Fix issue with connecting to configserver.
  samples/cloud-config/configclient/build.sh
Labels: type: task

#1107 Add note on Config Client support.
  spring-native-docs/src/main/asciidoc/support.adoc
Labels: type: documentation

#1112 Reduce ConfigServer hints.
  spring-native-configuration/src/main/java/org/springframework/cloud/config/server/ConfigServerHints.java
Labels: type: task

#1111 Reduce Sleuth hints.
  samples/zipkin-sleuth/src/main/java/com/example/zipkin/sleuth/ZipkinSleuthApplication.java
  spring-native-configuration/src/main/java/org/springframework/cloud/sleuth/TraceHints.java
Labels: type: task

#1116 Fix configserver and configclient setup
  samples/cloud-config/configclient/src/main/java/com/example/configclient/ConfigClientApplication.java
  samples/cloud-config/configclient/src/test/java/com/example/configclient/ConfigClientApplicationTests.java
  spring-native-configuration/src/main/java/org/springframework/cloud/config/client/ConfigClientHints.java
  spring-native-configuration/src/main/java/org/springframework/cloud/config/server/ConfigServerHints.java
Labels: type: task, theme: aot
