Repository spring-projects-experimental/spring-native, pull requests merged in 2021-11, with the labels that each got.

#1207 New sample for Spring Cloud Stream RabbitMQ Binder
  samples/cloud-stream-rabbit/.gitignore
  samples/cloud-stream-rabbit/README.md
  samples/cloud-stream-rabbit/build.sh
  samples/cloud-stream-rabbit/docker-compose.yml
  samples/cloud-stream-rabbit/pom.xml
  samples/cloud-stream-rabbit/src/main/java/com/example/demo/SpringCloudStreamRabbitApplication.java
  samples/cloud-stream-rabbit/src/main/resources/application.properties
  samples/cloud-stream-rabbit/verify.sh
  spring-native-configuration/pom.xml
  spring-native-configuration/src/main/java/org/springframework/cloud/stream/rabbit/RabbitBinderHints.java
  spring-native-configuration/src/main/resources/META-INF/services/org.springframework.nativex.type.NativeConfiguration
Labels: type: compatibility

#1222 Add Sleuth Brave Kafka config.
  spring-native-configuration/src/main/java/org/springframework/cloud/sleuth/TraceHints.java
Labels: status: waiting-for-triage

#1225 Corrected incorrect docker image name that is generated under asciidoc
  spring-native-docs/src/main/asciidoc/getting-started-buildpacks.adoc
Labels: type: documentation

#1250 Add more tests covering Spring Boot testing feature
  samples/boot-features/src/main/java/com/example/bootfeatures/RestTemplateClientService.java
  samples/boot-features/src/test/java/com/example/bootfeatures/RestTemplateClientServiceTests.java
  samples/webmvc-tomcat/src/test/java/com/example/webmvc/RandomPortTests.java
  samples/webmvc-tomcat/src/test/java/com/example/webmvc/RequestJsonTests.java
  samples/webmvc-tomcat/src/test/java/com/example/webmvc/WebmvcApplicationTests.java
  samples/webmvc-tomcat/src/test/java/com/example/webmvc/WebmvcControllerMockTests.java
  samples/webmvc-tomcat/src/test/java/com/example/webmvc/WebmvcSliceTests.java
Labels: type: task

#1265 Dynamically replace DITEL with AotDependencyInjectionTestExecutionListener
  spring-aot/src/main/java/org/springframework/aot/factories/TestExecutionListenerFactoriesCodeContributor.java
  spring-aot/src/test/java/org/springframework/aot/factories/TestExecutionListenerFactoriesCodeContributorTests.java
  spring-native/src/main/java/org/springframework/aot/test/AotDependencyInjectionTestExecutionListener.java
  spring-native/src/main/resources/META-INF/spring.factories
Labels: type: enhancement, theme: aot
