Repository spring-projects-experimental/spring-native, pull requests merged in 2021-06, with the labels that each got.

#811 Add substitution for Spring Data MongoDB LazyLoadingProxies
  samples/data-mongodb/src/main/java/com/example/data/mongo/CLR.java
  samples/data-mongodb/src/main/java/com/example/data/mongo/Coupon.java
  samples/data-mongodb/src/main/java/com/example/data/mongo/Order.java
  samples/data-mongodb/src/main/java/com/example/data/mongo/PriceReduction.java
  spring-aot/src/main/java/org/springframework/nativex/type/Field.java
  spring-native-configuration/src/main/java/org/springframework/boot/autoconfigure/data/mongodb/MongoRepositoriesHints.java
  spring-native/pom.xml
  spring-native/src/main/java/org/springframework/nativex/substitutions/data/Target_DefaultDbRefResolver.java
Labels: type: enhancement

#831 Added hint to support spring-integration-jdbc dependency.
  spring-native-configuration/pom.xml
  spring-native-configuration/src/main/java/org/springframework/integration/IntegrationHints.java
Labels: type: compatibility

#815 Adding Micrometer to supported projects
  spring-native-docs/src/main/asciidoc/support.adoc
Labels: type: documentation

#858 Fixed Buildpack URL link
  spring-native-docs/src/main/asciidoc/getting-started-buildpacks.adoc
Labels: type: documentation

#856 Update native image limitation page link
  spring-native-docs/src/main/asciidoc/index.adoc
Labels: type: documentation

#865 Update IntegrationHints.java
  spring-native-configuration/src/main/java/org/springframework/integration/IntegrationHints.java
Labels: type: compatibility
