Repository spring-projects-experimental/spring-native, pull requests merged in 2021-04, with the labels that each got.

#697 Hint for Kafka Consumer Proxies
  samples/kafka/src/main/java/com/example/kafka/KafkaApplication.java
  spring-native-configuration/src/main/java/org/springframework/kafka/annotation/KafkaHints.java
Labels: type: compatibility

#703 Upgrade to Maven 3.8.1
  .mvn/wrapper/maven-wrapper.properties
  samples/cloud-function-aws/.mvn/wrapper/maven-wrapper.properties
  samples/cloud-function-netty-fun/.mvn/wrapper/maven-wrapper.properties
  samples/cloud-function-netty/.mvn/wrapper/maven-wrapper.properties
  samples/cloud/.mvn/wrapper/maven-wrapper.properties
  samples/hibernate/.mvn/wrapper/maven-wrapper.properties
  samples/javamail/.mvn/wrapper/maven-wrapper.properties
  samples/lombok/.mvn/wrapper/maven-wrapper.properties
  samples/petclinic-jdbc/.mvn/wrapper/maven-wrapper.properties
  samples/petclinic-jpa/.mvn/wrapper/maven-wrapper.properties
  samples/security-webflux/.mvn/wrapper/maven-wrapper.properties
  samples/wavefront-sleuth/.mvn/wrapper/maven-wrapper.properties
  samples/wavefront/.mvn/wrapper/maven-wrapper.properties
  samples/webflux-kotlin/.mvn/wrapper/maven-wrapper.properties
  samples/webflux-netty/.mvn/wrapper/maven-wrapper.properties
  samples/webflux-thymeleaf/.mvn/wrapper/maven-wrapper.properties
  samples/webflux-websocket/.mvn/wrapper/maven-wrapper.properties
  samples/webmvc-tomcat-agent/.mvn/wrapper/maven-wrapper.properties
  samples/webmvc-tomcat/.mvn/wrapper/maven-wrapper.properties
Labels: type: task

#728 Add Thymeleaf expresssion language hints
  spring-native-configuration/src/main/java/org/thymeleaf/ThymeleafHints.java
Labels: status: waiting-for-triage

#750 Build pull requests on CI
  ci/pipeline.yml
  ci/tasks/build-pr-project.yml
Labels: type: task

#760 Polish Maven Plugin parameters names
  spring-aot-maven-plugin/src/main/java/org/springframework/aot/maven/GenerateMojo.java
  spring-aot-maven-plugin/src/main/java/org/springframework/aot/maven/TestGenerateMojo.java
Labels: theme: aot, type: enhancement
