Repository spring-projects-experimental/spring-native, pull requests merged in 2022-03, with the labels that each got.

#1520 Add cloud consul hints.
  spring-native-configuration/pom.xml
  spring-native-configuration/src/main/java/org/springframework/cloud/consul/CloudConsulHints.java
  spring-native-configuration/src/main/resources/META-INF/spring.factories
Labels: type: bug

#1525 Adds missing hints for TX with Sleuth
  samples/zipkin-sleuth/pom.xml
  samples/zipkin-sleuth/src/main/java/com/example/zipkin/sleuth/MyEntity.java
  samples/zipkin-sleuth/src/main/java/com/example/zipkin/sleuth/MyEntityRepository.java
  samples/zipkin-sleuth/src/test/java/com/example/zipkin/sleuth/test/ZipkinSleuthApplicationTest.java
  spring-native-configuration/src/main/java/org/springframework/cloud/sleuth/TraceHints.java
Labels: type: compatibility

#1537 Add Jackson PropertyNamingStrategies hint
  spring-native-configuration/src/main/java/org/springframework/boot/autoconfigure/jackson/JacksonHints.java
Labels: type: compatibility

#1545 Create CSV files correctly when running under german locale
  build-key-samples.sh
  build-samples-aot-only.sh
  build-samples-with-native-tests.sh
  build-samples.sh
Labels: type: task

#1548 Updates Neo4J to 4.4.5
  samples/data-neo4j/docker-compose.yml
Labels: type: task

#1553 Use mysql-server image
  samples/petclinic-jdbc/docker-compose.yml
  samples/petclinic-jpa/docker-compose.yml
Labels: type: task

#1560 Register TransactionalEventListener as a synthesized annotation
  spring-native-configuration/src/main/java/org/springframework/transaction/annotation/TransactionalEventListenerHints.java
  spring-native-configuration/src/main/resources/META-INF/spring.factories
Labels: status: waiting-for-triage

#1562 Fix native test failures with Graal 22.1
  spring-aot/src/main/java/org/springframework/aot/factories/IgnoredFactoriesCodeContributor.java
Labels: status: waiting-for-triage
